<?php
/**
 * Created by PhpStorm.
 * User: Wisdom Emenike
 * Date: 5/9/2020
 * Time: 7:20 PM
 */

namespace model;

use loan\Loan;
use que\database\model\Model;
use que\utility\money\Item;

class Wallet extends Model
{
    protected string $modelKey = 'walletModel';
    protected array $viewable = ['uuid', 'balance', 'available_balance', 'user_id', 'is_frozen', 'is_active'];
    protected array $casts = ['is_frozen,is_active' => 'bool'];


    public function getArray(bool $onlyFillable = false): array
    {
        $data = parent::getArray($onlyFillable);
        $data['balance'] = Item::cents($data['balance'])->getFactor();
        $data['available_balance'] = Item::cents($data['available_balance'])->getFactor();
        return $data; // TODO: Change the autogenerated stub
    }

    public function getUser() {
        return $this->belongTo('users', 'user_id');
    }

}
