<?php
/**
 * Created by PhpStorm.
 * User: Wisdom Emenike
 * Date: 4/15/2021
 * Time: 6:03 AM
 */

namespace middleware;


use que\http\input\Input;
use que\security\Middleware;
use que\security\MiddlewareResponse;
use que\support\Config;

class ExpireJWTMiddleware extends Middleware
{
    public function handle(Input $input): MiddlewareResponse
    {
        Config::set('auth.jwt.ttl', TIMEOUT_ONE_HOUR);
        return parent::handle($input); // TODO: Change the autogenerated stub
    }
}